import axios from 'axios';
import { isTest } from './test';

export interface FoodDTO {
  brand_name?: string;
  food_description: string;
  food_id: string;
  food_name: string;
  food_type: string;
  food_url: string;
  quantity: number;
  unit: string;
  calories: number;
  fat: number;
  carbs: number;
  protein: number;
}

export interface FoodsDTO {
  foods: FoodDTO[];
  max_results: string;
  page_number: string;
  total_results: string;
}

export const getFoods = async (search: string, page: number = 0): Promise<FoodDTO[]> => {
  if (isTest) return test.foods;
  try {
    const { data }: { data: FoodsDTO } = await axios.get(
      `${process.env.EXPO_PUBLIC_API_URL}/foods`,
      { timeout: 20000, params: { search, page, pageSize: 50 } },
    );
    return data.foods;
  } catch (error) {
    console.error(error);
    return [];
  }
};

const test: FoodsDTO = {
  foods: [
    {
      food_description:
        'Per 100g - Calories: 406kcal | Fat: 21.00g | Carbs: 45.80g | Protein: 8.20g',
      food_id: '3533',
      food_name: 'Croissant',
      food_type: 'Generic',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/croissant',
      quantity: 100,
      unit: 'g',
      calories: 406,
      fat: 21,
      carbs: 45.8,
      protein: 8.2,
    },
    {
      food_description: 'Per 100g - Calories: 29kcal | Fat: 0.30g | Carbs: 9.32g | Protein: 1.10g',
      food_id: '5268',
      food_name: 'Lemon',
      food_type: 'Generic',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/lemon-raw',
      quantity: 100,
      unit: 'g',
      calories: 29,
      fat: 0.3,
      carbs: 9.32,
      protein: 1.1,
    },
    {
      food_description:
        'Per 100g - Calories: 101kcal | Fat: 2.50g | Carbs: 11.50g | Protein: 8.00g',
      food_id: '1902',
      food_name: 'Lowfat Smoked Turkey, Pork and Beef Sausage',
      food_type: 'Generic',
      food_url:
        'https://www.fatsecret.com/calories-nutrition/generic/turkey-pork-and-beef-sausage-lowfat-smoked',
      quantity: 100,
      unit: 'g',
      calories: 101,
      fat: 2.5,
      carbs: 11.5,
      protein: 8,
    },
    {
      food_description:
        'Per 101g - Calories: 113kcal | Fat: 1.23g | Carbs: 0.00g | Protein: 23.50g',
      food_id: '1937',
      food_name: 'Cooked Fish',
      food_type: 'Generic',
      food_url:
        'https://www.fatsecret.com/calories-nutrition/generic/fish-cooked-ns-as-to-cooking-method',
      quantity: 101,
      unit: 'g',
      calories: 113,
      fat: 1.23,
      carbs: 0,
      protein: 23.5,
    },
    {
      food_description: 'Per 100g - Calories: 34kcal | Fat: 0.17g | Carbs: 4.86g | Protein: 3.26g',
      food_id: '820',
      food_name: 'Lowfat Dry Milk (Reconstituted)',
      food_type: 'Generic',
      food_url:
        'https://www.fatsecret.com/calories-nutrition/generic/milk-dry-reconstituted-lowfat',
      quantity: 100,
      unit: 'g',
      calories: 34,
      fat: 0.17,
      carbs: 4.86,
      protein: 3.26,
    },
    {
      food_description:
        'Per 100g - Calories: 296kcal | Fat: 24.00g | Carbs: 0.00g | Protein: 18.50g',
      food_id: '1871',
      food_name: 'Smoked Chicken and Beef Sausage',
      food_type: 'Generic',
      food_url:
        'https://www.fatsecret.com/calories-nutrition/generic/chicken-and-beef-sausage-smoked',
      quantity: 100,
      unit: 'g',
      calories: 296,
      fat: 24,
      carbs: 0,
      protein: 18.5,
    },
    {
      food_description:
        'Per 100g - Calories: 250kcal | Fat: 14.93g | Carbs: 0.00g | Protein: 27.10g',
      food_id: '1935',
      food_name: 'Corned Beef Spread',
      food_type: 'Generic',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/corned-beef-spread',
      quantity: 100,
      unit: 'g',
      calories: 250,
      fat: 14.93,
      carbs: 0,
      protein: 27.1,
    },
    {
      food_description:
        'Per 1086g - Calories: 2314kcal | Fat: 120.81g | Carbs: 89.63g | Protein: 207.30g',
      food_id: '1940',
      food_name: 'Fried Floured or Breaded Fish',
      food_type: 'Generic',
      food_url:
        'https://www.fatsecret.com/calories-nutrition/generic/fish-floured-or-breaded-fried',
      quantity: 1086,
      unit: 'g',
      calories: 2314,
      fat: 120.81,
      carbs: 89.63,
      protein: 207.3,
    },
    {
      food_description: 'Per 100g - Calories: 63kcal | Fat: 1.55g | Carbs: 7.04g | Protein: 5.25g',
      food_id: '845',
      food_name: 'Plain Yogurt',
      food_type: 'Generic',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/yogurt-plain',
      quantity: 100,
      unit: 'g',
      calories: 63,
      fat: 1.55,
      carbs: 7.04,
      protein: 5.25,
    },
    {
      food_description:
        'Per 100g - Calories: 250kcal | Fat: 20.11g | Carbs: 2.25g | Protein: 13.92g',
      food_id: '1888',
      food_name: 'Soft Salami',
      food_type: 'Generic',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/salami-soft-cooked',
      quantity: 100,
      unit: 'g',
      calories: 250,
      fat: 20.11,
      carbs: 2.25,
      protein: 13.92,
    },
    {
      food_description: 'Per 100g - Calories: 84kcal | Fat: 0.92g | Carbs: 0.00g | Protein: 17.76g',
      food_id: '1936',
      food_name: 'Fish',
      food_type: 'Generic',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/fish-raw',
      quantity: 100,
      unit: 'g',
      calories: 84,
      fat: 0.92,
      carbs: 0,
      protein: 17.76,
    },
    {
      food_description:
        'Per 100g - Calories: 249kcal | Fat: 13.25g | Carbs: 21.18g | Protein: 11.04g',
      food_id: '1947',
      food_name: 'Baked or Broiled Fish Stick Patty or Fillet',
      food_type: 'Generic',
      food_url:
        'https://www.fatsecret.com/calories-nutrition/generic/fish-stick-patty-or-fillet-baked-or-broiled',
      quantity: 100,
      unit: 'g',
      calories: 249,
      fat: 13.25,
      carbs: 21.18,
      protein: 11.04,
    },
    {
      food_description:
        'Per 980g - Calories: 323kcal | Fat: 0.69g | Carbs: 47.52g | Protein: 31.94g',
      food_id: '818',
      food_name: 'Dry Milk (Reconstituted)',
      food_type: 'Generic',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/milk-dry-reconstituted',
      quantity: 980,
      unit: 'g',
      calories: 323,
      fat: 0.69,
      carbs: 47.52,
      protein: 31.94,
    },
    {
      food_description: 'Per 100g - Calories: 86kcal | Fat: 1.18g | Carbs: 19.02g | Protein: 3.22g',
      food_id: '6243',
      food_name: 'Corn',
      food_type: 'Generic',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/corn-raw',
      quantity: 100,
      unit: 'g',
      calories: 86,
      fat: 1.18,
      carbs: 19.02,
      protein: 3.22,
    },
    {
      food_description:
        'Per 986g - Calories: 631kcal | Fat: 34.21g | Carbs: 49.20g | Protein: 33.72g',
      food_id: '819',
      food_name: 'Whole Dry Milk (Reconstituted)',
      food_type: 'Generic',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/milk-dry-reconstituted-whole',
      quantity: 986,
      unit: 'g',
      calories: 631,
      fat: 34.21,
      carbs: 49.2,
      protein: 33.72,
    },
    {
      food_description: 'Per 100g - Calories: 50kcal | Fat: 1.97g | Carbs: 4.68g | Protein: 3.30g',
      food_id: '800',
      food_name: '2% Fat Milk',
      food_type: 'Generic',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/milk-cows-fluid-2%25-fat',
      quantity: 100,
      unit: 'g',
      calories: 50,
      fat: 1.97,
      carbs: 4.68,
      protein: 3.3,
    },
    {
      food_description:
        'Per 100g - Calories: 240kcal | Fat: 16.80g | Carbs: 2.60g | Protein: 18.60g',
      food_id: '1901',
      food_name: 'Reduced Fat Smoked Turkey, Pork and Beef Sausage',
      food_type: 'Generic',
      food_url:
        'https://www.fatsecret.com/calories-nutrition/generic/turkey-pork-and-beef-sausage-reduced-fat-smoked',
      quantity: 100,
      unit: 'g',
      calories: 240,
      fat: 16.8,
      carbs: 2.6,
      protein: 18.6,
    },
    {
      food_description:
        'Per 920g - Calories: 349kcal | Fat: 5.24g | Carbs: 44.14g | Protein: 30.90g',
      food_id: '822',
      food_name: 'Dry Buttermilk (Reconstituted)',
      food_type: 'Generic',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/buttermilk-dry-reconstituted',
      quantity: 920,
      unit: 'g',
      calories: 349,
      fat: 5.24,
      carbs: 44.14,
      protein: 30.9,
    },
    {
      food_description:
        'Per 100g - Calories: 126kcal | Fat: 4.84g | Carbs: 2.04g | Protein: 17.50g',
      food_id: '1923',
      food_name: 'Turkey Ham',
      food_type: 'Generic',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/turkey-ham',
      quantity: 100,
      unit: 'g',
      calories: 126,
      fat: 4.84,
      carbs: 2.04,
      protein: 17.5,
    },
    {
      food_description:
        'Per 100g - Calories: 541kcal | Fat: 41.78g | Carbs: 1.43g | Protein: 37.04g',
      food_id: '1517',
      food_name: 'Bacon',
      food_type: 'Generic',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/bacon-cooked',
      quantity: 100,
      unit: 'g',
      calories: 541,
      fat: 41.78,
      carbs: 1.43,
      protein: 37.04,
    },
    {
      food_description:
        'Per 489g - Calories: 337kcal | Fat: 19.07g | Carbs: 25.28g | Protein: 17.16g',
      food_id: '826',
      food_name: 'Evaporated Milk (Diluted)',
      food_type: 'Generic',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/milk-evaporated-diluted',
      quantity: 489,
      unit: 'g',
      calories: 337,
      fat: 19.07,
      carbs: 25.28,
      protein: 17.16,
    },
    {
      food_description: 'Per 102g - Calories: 94kcal | Fat: 2.00g | Carbs: 11.35g | Protein: 7.55g',
      food_id: '832',
      food_name: '2% Fat Evaporated Milk (Undiluted)',
      food_type: 'Generic',
      food_url:
        'https://www.fatsecret.com/calories-nutrition/generic/milk-evaporated-2%25-fat-undiluted',
      quantity: 102,
      unit: 'g',
      calories: 94,
      fat: 2,
      carbs: 11.35,
      protein: 7.55,
    },
    {
      food_description:
        'Per 100g - Calories: 334kcal | Fat: 30.30g | Carbs: 2.10g | Protein: 12.50g',
      food_id: '1911',
      food_name: 'Ham Meat Loaf',
      food_type: 'Generic',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/ham-loaf-luncheon-meat',
      quantity: 100,
      unit: 'g',
      calories: 334,
      fat: 30.3,
      carbs: 2.1,
      protein: 12.5,
    },
    {
      food_description:
        'Per 498g - Calories: 239kcal | Fat: 5.08g | Carbs: 29.06g | Protein: 19.36g',
      food_id: '833',
      food_name: '2% Fat Evaporated Milk (Diluted)',
      food_type: 'Generic',
      food_url:
        'https://www.fatsecret.com/calories-nutrition/generic/milk-evaporated-2%25-fat-diluted',
      quantity: 498,
      unit: 'g',
      calories: 239,
      fat: 5.08,
      carbs: 29.06,
      protein: 19.36,
    },
    {
      food_description:
        'Per 100g - Calories: 110kcal | Fat: 2.86g | Carbs: 2.63g | Protein: 17.28g',
      food_id: '1869',
      food_name: 'Capicola',
      food_type: 'Generic',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/capicola',
      quantity: 100,
      unit: 'g',
      calories: 110,
      fat: 2.86,
      carbs: 2.63,
      protein: 17.28,
    },
    {
      food_description:
        'Per 100g - Calories: 362kcal | Fat: 30.43g | Carbs: 3.33g | Protein: 17.45g',
      food_id: '1870',
      food_name: 'Soft Cervelat',
      food_type: 'Generic',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/cervelat-soft',
      quantity: 100,
      unit: 'g',
      calories: 362,
      fat: 30.43,
      carbs: 3.33,
      protein: 17.45,
    },
    {
      food_description:
        'Per 100g - Calories: 149kcal | Fat: 7.10g | Carbs: 0.88g | Protein: 19.10g',
      food_id: '1928',
      food_name: 'Deli Sliced Beef Luncheon Meat',
      food_type: 'Generic',
      food_url:
        'https://www.fatsecret.com/calories-nutrition/generic/beef-sliced-prepackaged-or-deli-luncheon-meat',
      quantity: 100,
      unit: 'g',
      calories: 149,
      fat: 7.1,
      carbs: 0.88,
      protein: 19.1,
    },
    {
      food_description:
        'Per 1172g - Calories: 2343kcal | Fat: 108.02g | Carbs: 100.64g | Protein: 228.22g',
      food_id: '1939',
      food_name: 'Baked Breaded or Battered Fish',
      food_type: 'Generic',
      food_url:
        'https://www.fatsecret.com/calories-nutrition/generic/fish-breaded-or-battered-baked',
      quantity: 1172,
      unit: 'g',
      calories: 2343,
      fat: 108.02,
      carbs: 100.64,
      protein: 228.22,
    },
    {
      food_description: 'Per 100g - Calories: 34kcal | Fat: 0.08g | Carbs: 4.96g | Protein: 3.37g',
      food_id: '810',
      food_name: 'Nonfat Lactose Reduced Milk',
      food_type: 'Generic',
      food_url:
        'https://www.fatsecret.com/calories-nutrition/generic/milk-cows-fluid-lactose-reduced-nonfat',
      quantity: 100,
      unit: 'g',
      calories: 34,
      fat: 0.08,
      carbs: 4.96,
      protein: 3.37,
    },
    {
      food_description: 'Per 100g - Calories: 42kcal | Fat: 1.66g | Carbs: 3.65g | Protein: 3.22g',
      food_id: '841',
      food_name: 'Ready-to-Drink Soy Milk',
      food_type: 'Generic',
      food_url:
        'https://www.fatsecret.com/calories-nutrition/generic/milk-soy-ready-to-drink-not-babys',
      quantity: 100,
      unit: 'g',
      calories: 42,
      fat: 1.66,
      carbs: 3.65,
      protein: 3.22,
    },
    {
      food_description:
        'Per 100g - Calories: 407kcal | Fat: 37.63g | Carbs: 2.36g | Protein: 13.70g',
      food_id: '1883',
      food_name: 'Brown and Serve Pork Sausage Rice Links',
      food_type: 'Generic',
      food_url:
        'https://www.fatsecret.com/calories-nutrition/generic/pork-sausage-rice-links-brown-and-serve-cooked',
      quantity: 100,
      unit: 'g',
      calories: 407,
      fat: 37.63,
      carbs: 2.36,
      protein: 13.7,
    },
    {
      food_description: 'Per 100g - Calories: 61kcal | Fat: 3.25g | Carbs: 4.66g | Protein: 3.47g',
      food_id: '846',
      food_name: 'Whole Milk Plain Yogurt',
      food_type: 'Generic',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/yogurt-plain-whole-milk',
      quantity: 100,
      unit: 'g',
      calories: 61,
      fat: 3.25,
      carbs: 4.66,
      protein: 3.47,
    },
    {
      food_description:
        'Per 100g - Calories: 396kcal | Fat: 36.25g | Carbs: 2.70g | Protein: 13.80g',
      food_id: '1885',
      food_name: 'Brown and Serve Pork and Beef Sausage',
      food_type: 'Generic',
      food_url:
        'https://www.fatsecret.com/calories-nutrition/generic/pork-and-beef-sausage-brown-and-serve-cooked',
      quantity: 100,
      unit: 'g',
      calories: 396,
      fat: 36.25,
      carbs: 2.7,
      protein: 13.8,
    },
    {
      food_description:
        'Per 100g - Calories: 110kcal | Fat: 2.86g | Carbs: 2.63g | Protein: 17.28g',
      food_id: '1909',
      food_name: 'Extra Lean Deli Sliced Ham',
      food_type: 'Generic',
      food_url:
        'https://www.fatsecret.com/calories-nutrition/generic/ham-sliced-extra-lean-prepackaged-or-deli-luncheon-meat',
      quantity: 100,
      unit: 'g',
      calories: 110,
      fat: 2.86,
      carbs: 2.63,
      protein: 17.28,
    },
    {
      food_description:
        'Per 100g - Calories: 210kcal | Fat: 9.71g | Carbs: 0.00g | Protein: 28.89g',
      food_id: '1952',
      food_name: 'Canned Anchovy',
      food_type: 'Generic',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/anchovy-canned',
      quantity: 100,
      unit: 'g',
      calories: 210,
      fat: 9.71,
      carbs: 0,
      protein: 28.89,
    },
    {
      food_description:
        'Per 100g - Calories: 227kcal | Fat: 14.76g | Carbs: 14.96g | Protein: 8.57g',
      food_id: '1891',
      food_name: 'Cooked Scrapple',
      food_type: 'Generic',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/scrapple-cooked',
      quantity: 100,
      unit: 'g',
      calories: 227,
      fat: 14.76,
      carbs: 14.96,
      protein: 8.57,
    },
    {
      food_description:
        'Per 100g - Calories: 315kcal | Fat: 26.60g | Carbs: 4.60g | Protein: 13.40g',
      food_id: '1916',
      food_name: 'Spiced Minced Chopped Ham and Pork (Canned)',
      food_type: 'Generic',
      food_url:
        'https://www.fatsecret.com/calories-nutrition/generic/ham-and-pork-luncheon-meat-chopped-minced-pressed-spiced-canned',
      quantity: 100,
      unit: 'g',
      calories: 315,
      fat: 26.6,
      carbs: 4.6,
      protein: 13.4,
    },
    {
      food_description:
        'Per 133g - Calories: 265kcal | Fat: 15.12g | Carbs: 8.92g | Protein: 22.24g',
      food_id: '1941',
      food_name: 'Fried Battered Fish',
      food_type: 'Generic',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/fish-battered-fried',
      quantity: 133,
      unit: 'g',
      calories: 265,
      fat: 15.12,
      carbs: 8.92,
      protein: 22.24,
    },
    {
      food_description:
        'Per 101g - Calories: 197kcal | Fat: 7.79g | Carbs: 0.00g | Protein: 29.80g',
      food_id: '1641',
      food_name: 'Chicken Breast',
      food_type: 'Generic',
      food_url:
        'https://www.fatsecret.com/calories-nutrition/generic/chicken-breast-ns-as-to-skin-eaten',
      quantity: 101,
      unit: 'g',
      calories: 197,
      fat: 7.79,
      carbs: 0,
      protein: 29.8,
    },
    {
      food_description:
        'Per 101g - Calories: 290kcal | Fat: 23.39g | Carbs: 2.62g | Protein: 16.19g',
      food_id: '1905',
      food_name: 'Pickled Sausage',
      food_type: 'Generic',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/pickled-sausage',
      quantity: 101,
      unit: 'g',
      calories: 290,
      fat: 23.39,
      carbs: 2.62,
      protein: 16.19,
    },
    {
      food_description:
        'Per 100g - Calories: 200kcal | Fat: 13.52g | Carbs: 7.41g | Protein: 11.64g',
      food_id: '1931',
      food_name: 'Chicken Salad Spread',
      food_type: 'Generic',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/chicken-salad-spread',
      quantity: 100,
      unit: 'g',
      calories: 200,
      fat: 13.52,
      carbs: 7.41,
      protein: 11.64,
    },
    {
      food_description:
        'Per 100g - Calories: 339kcal | Fat: 28.36g | Carbs: 0.00g | Protein: 19.43g',
      food_id: '1882',
      food_name: 'Country Style Pork Sausage',
      food_type: 'Generic',
      food_url:
        'https://www.fatsecret.com/calories-nutrition/generic/pork-sausage-country-style-fresh-cooked',
      quantity: 100,
      unit: 'g',
      calories: 339,
      fat: 28.36,
      carbs: 0,
      protein: 19.43,
    },
    {
      food_description: 'Per 100g - Calories: 60kcal | Fat: 3.25g | Carbs: 4.52g | Protein: 3.22g',
      food_id: '813',
      food_name: 'Lactose Reduced Whole Milk',
      food_type: 'Generic',
      food_url:
        'https://www.fatsecret.com/calories-nutrition/generic/milk-cows-fluid-lactose-reduced-whole',
      quantity: 100,
      unit: 'g',
      calories: 60,
      fat: 3.25,
      carbs: 4.52,
      protein: 3.22,
    },
    {
      food_description: 'Per 100g - Calories: 56kcal | Fat: 0.18g | Carbs: 7.68g | Protein: 5.73g',
      food_id: '848',
      food_name: 'Nonfat Plain Yogurt',
      food_type: 'Generic',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/yogurt-plain-nonfat-milk',
      quantity: 100,
      unit: 'g',
      calories: 56,
      fat: 0.18,
      carbs: 7.68,
      protein: 5.73,
    },
    {
      food_description:
        'Per 100g - Calories: 139kcal | Fat: 2.90g | Carbs: 0.00g | Protein: 26.34g',
      food_id: '1942',
      food_name: 'Steamed Fish',
      food_type: 'Generic',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/fish-steamed',
      quantity: 100,
      unit: 'g',
      calories: 139,
      fat: 2.9,
      carbs: 0,
      protein: 26.34,
    },
    {
      food_description:
        'Per 972g - Calories: 2051kcal | Fat: 117.21g | Carbs: 3.99g | Protein: 227.81g',
      food_id: '1953',
      food_name: 'Barracuda',
      food_type: 'Generic',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/barracuda-cooked',
      quantity: 972,
      unit: 'g',
      calories: 2051,
      fat: 117.21,
      carbs: 3.99,
      protein: 227.81,
    },
    {
      food_description:
        'Per 100g - Calories: 230kcal | Fat: 16.23g | Carbs: 8.83g | Protein: 11.52g',
      food_id: '1920',
      food_name: 'Olive, Pickle or Pimiento Luncheon Loaf',
      food_type: 'Generic',
      food_url:
        'https://www.fatsecret.com/calories-nutrition/generic/luncheon-loaf-(olive-pickle-or-pimiento)',
      quantity: 100,
      unit: 'g',
      calories: 230,
      fat: 16.23,
      carbs: 8.83,
      protein: 11.52,
    },
    {
      food_description: 'Per 100g - Calories: 85kcal | Fat: 1.25g | Carbs: 13.80g | Protein: 4.93g',
      food_id: '849',
      food_name: 'Vanilla, Lemon or Coffee Flavor Yogurt',
      food_type: 'Generic',
      food_url:
        'https://www.fatsecret.com/calories-nutrition/generic/yogurt-vanilla-lemon-or-coffee-flavor',
      quantity: 100,
      unit: 'g',
      calories: 85,
      fat: 1.25,
      carbs: 13.8,
      protein: 4.93,
    },
    {
      food_description:
        'Per 100g - Calories: 290kcal | Fat: 2.37g | Carbs: 0.00g | Protein: 62.82g',
      food_id: '1943',
      food_name: 'Dried Fish',
      food_type: 'Generic',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/fish-dried',
      quantity: 100,
      unit: 'g',
      calories: 290,
      fat: 2.37,
      carbs: 0,
      protein: 62.82,
    },
    {
      food_description:
        'Per 691g - Calories: 1402kcal | Fat: 80.12g | Carbs: 4.42g | Protein: 156.37g',
      food_id: '1958',
      food_name: 'Baked or Broiled Carp',
      food_type: 'Generic',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/carp-baked-or-broiled',
      quantity: 691,
      unit: 'g',
      calories: 1402,
      fat: 80.12,
      carbs: 4.42,
      protein: 156.37,
    },
  ],
  max_results: '50',
  page_number: '0',
  total_results: '2066',
};
