import axios from 'axios';
import { isTest } from './test';

export interface FoodDTO {
  brand_name?: string;
  food_description: string;
  food_id: string;
  food_name: string;
  food_type: string;
  food_url: string;
  quantity: number;
  unit: string;
  calories: number;
  fat: number;
  carbs: number;
  protein: number;
}

export interface FoodsDTO {
  foods: FoodDTO[];
  max_results: string;
  page_number: string;
  total_results: string;
}

const unnacent = (text: string) => {
  return text.normalize('NFD').replace(/[\u0300-\u036f]/g, '');
};

export const getFoods = async (search: string, page: number = 0): Promise<FoodDTO[]> => {
  if (isTest)
    return test.foods.filter((food) =>
      unnacent(food.food_name).toUpperCase().includes(unnacent(search.toUpperCase())),
    );
  try {
    const { data }: { data: FoodsDTO } = await axios.get(
      `${process.env.EXPO_PUBLIC_API_URL}/foods`,
      { timeout: 20000, params: { search, page, pageSize: 50 } },
    );
    if (!data.foods) return [];
    return data?.foods;
  } catch (error) {
    console.error(error);
    return [];
  }
};

const test: FoodsDTO = {
  foods: [
    {
      food_description:
        'Por 100g - Calorias: 406kcal | Gordura: 21.00g | Carboidratos: 45.80g | Proteína: 8.20g',
      food_id: '3533',
      food_name: 'Croissant',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/croissant',
      quantity: 100,
      unit: 'g',
      calories: 406,
      fat: 21,
      carbs: 45.8,
      protein: 8.2,
    },
    {
      food_description:
        'Por 100g - Calorias: 29kcal | Gordura: 0.30g | Carboidratos: 9.32g | Proteína: 1.10g',
      food_id: '5268',
      food_name: 'Limão',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/lemon-raw',
      quantity: 100,
      unit: 'g',
      calories: 29,
      fat: 0.3,
      carbs: 9.32,
      protein: 1.1,
    },
    {
      food_description:
        'Por 100g - Calorias: 101kcal | Gordura: 2.50g | Carboidratos: 11.50g | Proteína: 8.00g',
      food_id: '1902',
      food_name: 'Salsicha de Peru, Porco e Carne de Vaca Defumada com Baixo Teor de Gordura',
      food_type: 'Genérico',
      food_url:
        'https://www.fatsecret.com/calories-nutrition/generic/turkey-pork-and-beef-sausage-lowfat-smoked',
      quantity: 100,
      unit: 'g',
      calories: 101,
      fat: 2.5,
      carbs: 11.5,
      protein: 8,
    },
    {
      food_description:
        'Por 101g - Calorias: 113kcal | Gordura: 1.23g | Carboidratos: 0.00g | Proteína: 23.50g',
      food_id: '1937',
      food_name: 'Peixe Cozido',
      food_type: 'Genérico',
      food_url:
        'https://www.fatsecret.com/calories-nutrition/generic/fish-cooked-ns-as-to-cooking-method',
      quantity: 101,
      unit: 'g',
      calories: 113,
      fat: 1.23,
      carbs: 0,
      protein: 23.5,
    },
    {
      food_description:
        'Por 100g - Calorias: 34kcal | Gordura: 0.17g | Carboidratos: 4.86g | Proteína: 3.26g',
      food_id: '820',
      food_name: 'Leite Desnatado em Pó (Reconstituído)',
      food_type: 'Genérico',
      food_url:
        'https://www.fatsecret.com/calories-nutrition/generic/milk-dry-reconstituted-lowfat',
      quantity: 100,
      unit: 'g',
      calories: 34,
      fat: 0.17,
      carbs: 4.86,
      protein: 3.26,
    },
    {
      food_description:
        'Por 100g - Calorias: 296kcal | Gordura: 24.00g | Carboidratos: 0.00g | Proteína: 18.50g',
      food_id: '1871',
      food_name: 'Salsicha Defumada de Frango e Carne de Vaca',
      food_type: 'Genérico',
      food_url:
        'https://www.fatsecret.com/calories-nutrition/generic/chicken-and-beef-sausage-smoked',
      quantity: 100,
      unit: 'g',
      calories: 296,
      fat: 24,
      carbs: 0,
      protein: 18.5,
    },
    {
      food_description:
        'Por 100g - Calorias: 250kcal | Gordura: 14.93g | Carboidratos: 0.00g | Proteína: 27.10g',
      food_id: '1935',
      food_name: 'Patê de Carne de Vaca',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/corned-beef-spread',
      quantity: 100,
      unit: 'g',
      calories: 250,
      fat: 14.93,
      carbs: 0,
      protein: 27.1,
    },
    {
      food_description:
        'Por 1086g - Calorias: 2314kcal | Gordura: 120.81g | Carboidratos: 89.63g | Proteína: 207.30g',
      food_id: '1940',
      food_name: 'Peixe Frito Empanado ou Enfarinhado',
      food_type: 'Genérico',
      food_url:
        'https://www.fatsecret.com/calories-nutrition/generic/fish-floured-or-breaded-fried',
      quantity: 1086,
      unit: 'g',
      calories: 2314,
      fat: 120.81,
      carbs: 89.63,
      protein: 207.3,
    },
    {
      food_description:
        'Por 100g - Calorias: 63kcal | Gordura: 1.55g | Carboidratos: 7.04g | Proteína: 5.25g',
      food_id: '845',
      food_name: 'Iogurte Natural',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/yogurt-plain',
      quantity: 100,
      unit: 'g',
      calories: 63,
      fat: 1.55,
      carbs: 7.04,
      protein: 5.25,
    },
    {
      food_description:
        'Por 100g - Calorias: 250kcal | Gordura: 20.11g | Carboidratos: 2.25g | Proteína: 13.92g',
      food_id: '1888',
      food_name: 'Salame Mole',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/salami-soft-cooked',
      quantity: 100,
      unit: 'g',
      calories: 250,
      fat: 20.11,
      carbs: 2.25,
      protein: 13.92,
    },
    {
      food_description:
        'Por 100g - Calorias: 84kcal | Gordura: 0.92g | Carboidratos: 0.00g | Proteína: 17.76g',
      food_id: '1936',
      food_name: 'Peixe',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/fish-raw',
      quantity: 100,
      unit: 'g',
      calories: 84,
      fat: 0.92,
      carbs: 0,
      protein: 17.76,
    },
    {
      food_description:
        'Por 100g - Calorias: 249kcal | Gordura: 13.25g | Carboidratos: 21.18g | Proteína: 11.04g',
      food_id: '1947',
      food_name: 'Palito, Hambúrguer ou Filé de Peixe Assado ou Grelhado',
      food_type: 'Genérico',
      food_url:
        'https://www.fatsecret.com/calories-nutrition/generic/fish-stick-patty-or-fillet-baked-or-broiled',
      quantity: 100,
      unit: 'g',
      calories: 249,
      fat: 13.25,
      carbs: 21.18,
      protein: 11.04,
    },
    {
      food_description:
        'Por 980g - Calorias: 323kcal | Gordura: 0.69g | Carboidratos: 47.52g | Proteína: 31.94g',
      food_id: '818',
      food_name: 'Leite em Pó (Reconstituído)',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/milk-dry-reconstituted',
      quantity: 980,
      unit: 'g',
      calories: 323,
      fat: 0.69,
      carbs: 47.52,
      protein: 31.94,
    },
    {
      food_description:
        'Por 100g - Calorias: 86kcal | Gordura: 1.18g | Carboidratos: 19.02g | Proteína: 3.22g',
      food_id: '1988',
      food_name: 'Feijão Preto Cozido',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/black-beans-cooked',
      quantity: 100,
      unit: 'g',
      calories: 86,
      fat: 1.18,
      carbs: 19.02,
      protein: 3.22,
    },
    {
      food_description:
        'Por 100g - Calorias: 41kcal | Gordura: 0.30g | Carboidratos: 10.11g | Proteína: 1.00g',
      food_id: '1924',
      food_name: 'Pepino',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/cucumber',
      quantity: 100,
      unit: 'g',
      calories: 41,
      fat: 0.3,
      carbs: 10.11,
      protein: 1,
    },
    {
      food_description:
        'Por 100g - Calorias: 119kcal | Gordura: 0.40g | Carboidratos: 25.50g | Proteína: 3.30g',
      food_id: '804',
      food_name: 'Maçã',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/apple',
      quantity: 100,
      unit: 'g',
      calories: 119,
      fat: 0.4,
      carbs: 25.5,
      protein: 3.3,
    },
    {
      food_description:
        'Por 100g - Calorias: 38kcal | Gordura: 0.60g | Carboidratos: 7.20g | Proteína: 1.50g',
      food_id: '807',
      food_name: 'Abóbora',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/pumpkin',
      quantity: 100,
      unit: 'g',
      calories: 38,
      fat: 0.6,
      carbs: 7.2,
      protein: 1.5,
    },
    {
      food_description:
        'Por 100g - Calorias: 49kcal | Gordura: 0.10g | Carboidratos: 12.30g | Proteína: 0.50g',
      food_id: '813',
      food_name: 'Tomate',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/tomato',
      quantity: 100,
      unit: 'g',
      calories: 49,
      fat: 0.1,
      carbs: 12.3,
      protein: 0.5,
    },
    {
      food_description:
        'Por 100g - Calorias: 54kcal | Gordura: 0.40g | Carboidratos: 14.10g | Proteína: 1.20g',
      food_id: '801',
      food_name: 'Banana',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/banana',
      quantity: 100,
      unit: 'g',
      calories: 54,
      fat: 0.4,
      carbs: 14.1,
      protein: 1.2,
    },
    {
      food_description:
        'Por 100g - Calorias: 50kcal | Gordura: 0.40g | Carboidratos: 11.70g | Proteína: 1.10g',
      food_id: '808',
      food_name: 'Manga',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/mango',
      quantity: 100,
      unit: 'g',
      calories: 50,
      fat: 0.4,
      carbs: 11.7,
      protein: 1.1,
    },
    {
      food_description:
        'Por 100g - Calorias: 20kcal | Gordura: 0.10g | Carboidratos: 4.80g | Proteína: 0.80g',
      food_id: '803',
      food_name: 'Melancia',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/watermelon',
      quantity: 100,
      unit: 'g',
      calories: 20,
      fat: 0.1,
      carbs: 4.8,
      protein: 0.8,
    },
    {
      food_description:
        'Por 100g - Calorias: 50kcal | Gordura: 0.40g | Carboidratos: 12.20g | Proteína: 0.60g',
      food_id: '809',
      food_name: 'Abacaxi',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/pineapple',
      quantity: 100,
      unit: 'g',
      calories: 50,
      fat: 0.4,
      carbs: 12.2,
      protein: 0.6,
    },
    {
      food_description:
        'Por 100g - Calorias: 18kcal | Gordura: 0.10g | Carboidratos: 3.90g | Proteína: 1.00g',
      food_id: '810',
      food_name: 'Melão',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/cantaloupe',
      quantity: 100,
      unit: 'g',
      calories: 18,
      fat: 0.1,
      carbs: 3.9,
      protein: 1,
    },
    {
      food_description:
        'Por 100g - Calorias: 30kcal | Gordura: 0.10g | Carboidratos: 6.80g | Proteína: 1.10g',
      food_id: '811',
      food_name: 'Laranja',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/orange',
      quantity: 100,
      unit: 'g',
      calories: 30,
      fat: 0.1,
      carbs: 6.8,
      protein: 1.1,
    },
    {
      food_description:
        'Por 100g - Calorias: 50kcal | Gordura: 0.30g | Carboidratos: 11.80g | Proteína: 0.70g',
      food_id: '812',
      food_name: 'Pêssego',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/peach',
      quantity: 100,
      unit: 'g',
      calories: 50,
      fat: 0.3,
      carbs: 11.8,
      protein: 0.7,
    },
    {
      food_description:
        'Por 100g - Calorias: 41kcal | Gordura: 0.10g | Carboidratos: 10.00g | Proteína: 0.40g',
      food_id: '814',
      food_name: 'Pêra',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/pear',
      quantity: 100,
      unit: 'g',
      calories: 41,
      fat: 0.1,
      carbs: 10,
      protein: 0.4,
    },
    {
      food_description:
        'Por 100g - Calorias: 90kcal | Gordura: 0.40g | Carboidratos: 22.50g | Proteína: 1.00g',
      food_id: '815',
      food_name: 'Uva',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/grapes',
      quantity: 100,
      unit: 'g',
      calories: 90,
      fat: 0.4,
      carbs: 22.5,
      protein: 1,
    },
    {
      food_description:
        'Por 100g - Calorias: 97kcal | Gordura: 0.50g | Carboidratos: 24.00g | Proteína: 1.00g',
      food_id: '805',
      food_name: 'Ameixa',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/plum',
      quantity: 100,
      unit: 'g',
      calories: 97,
      fat: 0.5,
      carbs: 24,
      protein: 1,
    },
    {
      food_description:
        'Por 100g - Calorias: 103kcal | Gordura: 0.80g | Carboidratos: 23.80g | Proteína: 0.50g',
      food_id: '806',
      food_name: 'Cereja',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/cherry',
      quantity: 100,
      unit: 'g',
      calories: 103,
      fat: 0.8,
      carbs: 23.8,
      protein: 0.5,
    },
    {
      food_description:
        'Por 100g - Calorias: 49kcal | Gordura: 0.30g | Carboidratos: 12.00g | Proteína: 0.70g',
      food_id: '819',
      food_name: 'Leite (Totalmente Desnatado)',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/milk-whole',
      quantity: 100,
      unit: 'g',
      calories: 49,
      fat: 0.3,
      carbs: 12,
      protein: 0.7,
    },
    {
      food_description:
        'Por 100g - Calorias: 81kcal | Gordura: 1.00g | Carboidratos: 18.00g | Proteína: 2.00g',
      food_id: '817',
      food_name: 'Batata',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/potato',
      quantity: 100,
      unit: 'g',
      calories: 81,
      fat: 1,
      carbs: 18,
      protein: 2,
    },
    {
      food_description:
        'Por 100g - Calorias: 23kcal | Gordura: 0.00g | Carboidratos: 5.50g | Proteína: 1.00g',
      food_id: '816',
      food_name: 'Cenoura',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/carrot',
      quantity: 100,
      unit: 'g',
      calories: 23,
      fat: 0,
      carbs: 5.5,
      protein: 1,
    },
    {
      food_description:
        'Por 100g - Calorias: 41kcal | Gordura: 0.10g | Carboidratos: 10.10g | Proteína: 1.10g',
      food_id: '802',
      food_name: 'Milho',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/corn',
      quantity: 100,
      unit: 'g',
      calories: 41,
      fat: 0.1,
      carbs: 10.1,
      protein: 1.1,
    },
    {
      food_description:
        'Por 100g - Calorias: 100kcal | Gordura: 1.30g | Carboidratos: 22.00g | Proteína: 2.50g',
      food_id: '823',
      food_name: 'Arroz Cozido',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/cooked-rice',
      quantity: 100,
      unit: 'g',
      calories: 100,
      fat: 1.3,
      carbs: 22,
      protein: 2.5,
    },
    {
      food_description:
        'Por 100g - Calorias: 160kcal | Gordura: 4.50g | Carboidratos: 29.00g | Proteína: 3.10g',
      food_id: '830',
      food_name: 'Macarrão Cozido',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/cooked-pasta',
      quantity: 100,
      unit: 'g',
      calories: 160,
      fat: 4.5,
      carbs: 29,
      protein: 3.1,
    },
    {
      food_description:
        'Por 100g - Calorias: 82kcal | Gordura: 0.50g | Carboidratos: 18.00g | Proteína: 1.30g',
      food_id: '828',
      food_name: 'Batata Doce',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/sweet-potato',
      quantity: 100,
      unit: 'g',
      calories: 82,
      fat: 0.5,
      carbs: 18,
      protein: 1.3,
    },
    {
      food_description:
        'Por 100g - Calorias: 33kcal | Gordura: 0.40g | Carboidratos: 6.20g | Proteína: 0.90g',
      food_id: '831',
      food_name: 'Brócolis Cozido',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/cooked-broccoli',
      quantity: 100,
      unit: 'g',
      calories: 33,
      fat: 0.4,
      carbs: 6.2,
      protein: 0.9,
    },
    {
      food_description:
        'Por 100g - Calorias: 28kcal | Gordura: 0.10g | Carboidratos: 5.70g | Proteína: 1.10g',
      food_id: '829',
      food_name: 'Aspargo Cozido',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/cooked-asparagus',
      quantity: 100,
      unit: 'g',
      calories: 28,
      fat: 0.1,
      carbs: 5.7,
      protein: 1.1,
    },
    {
      food_description:
        'Por 100g - Calorias: 35kcal | Gordura: 0.10g | Carboidratos: 8.10g | Proteína: 1.20g',
      food_id: '832',
      food_name: 'Beterraba Cozida',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/cooked-beet',
      quantity: 100,
      unit: 'g',
      calories: 35,
      fat: 0.1,
      carbs: 8.1,
      protein: 1.2,
    },
    {
      food_description:
        'Por 100g - Calorias: 17kcal | Gordura: 0.20g | Carboidratos: 2.50g | Proteína: 1.50g',
      food_id: '833',
      food_name: 'Couve Cozida',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/cooked-cabbage',
      quantity: 100,
      unit: 'g',
      calories: 17,
      fat: 0.2,
      carbs: 2.5,
      protein: 1.5,
    },
    {
      food_description:
        'Por 100g - Calorias: 48kcal | Gordura: 0.20g | Carboidratos: 11.00g | Proteína: 0.90g',
      food_id: '834',
      food_name: 'Cenoura Cozida',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/cooked-carrot',
      quantity: 100,
      unit: 'g',
      calories: 48,
      fat: 0.2,
      carbs: 11,
      protein: 0.9,
    },
    {
      food_description:
        'Por 100g - Calorias: 32kcal | Gordura: 0.10g | Carboidratos: 7.30g | Proteína: 1.20g',
      food_id: '835',
      food_name: 'Couve-Flor Cozida',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/cooked-cauliflower',
      quantity: 100,
      unit: 'g',
      calories: 32,
      fat: 0.1,
      carbs: 7.3,
      protein: 1.2,
    },
    {
      food_description:
        'Por 100g - Calorias: 44kcal | Gordura: 0.40g | Carboidratos: 10.20g | Proteína: 1.00g',
      food_id: '836',
      food_name: 'Milho Cozido',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/cooked-corn',
      quantity: 100,
      unit: 'g',
      calories: 44,
      fat: 0.4,
      carbs: 10.2,
      protein: 1,
    },
    {
      food_description:
        'Por 100g - Calorias: 22kcal | Gordura: 0.20g | Carboidratos: 4.10g | Proteína: 1.10g',
      food_id: '837',
      food_name: 'Cogumelo Cozido',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/cooked-mushroom',
      quantity: 100,
      unit: 'g',
      calories: 22,
      fat: 0.2,
      carbs: 4.1,
      protein: 1.1,
    },
    {
      food_description:
        'Por 100g - Calorias: 35kcal | Gordura: 0.20g | Carboidratos: 7.80g | Proteína: 1.30g',
      food_id: '838',
      food_name: 'Cebola Cozida',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/cooked-onion',
      quantity: 100,
      unit: 'g',
      calories: 35,
      fat: 0.2,
      carbs: 7.8,
      protein: 1.3,
    },
    {
      food_description:
        'Por 100g - Calorias: 27kcal | Gordura: 0.20g | Carboidratos: 4.60g | Proteína: 1.40g',
      food_id: '839',
      food_name: 'Espinafre Cozido',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/cooked-spinach',
      quantity: 100,
      unit: 'g',
      calories: 27,
      fat: 0.2,
      carbs: 4.6,
      protein: 1.4,
    },
    {
      food_description:
        'Por 100g - Calorias: 40kcal | Gordura: 0.30g | Carboidratos: 8.30g | Proteína: 1.80g',
      food_id: '840',
      food_name: 'Abobrinha Cozida',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/cooked-zucchini',
      quantity: 100,
      unit: 'g',
      calories: 40,
      fat: 0.3,
      carbs: 8.3,
      protein: 1.8,
    },
    {
      food_description:
        'Por 100g - Calorias: 70kcal | Gordura: 4.80g | Carboidratos: 1.10g | Proteína: 5.60g',
      food_id: '841',
      food_name: 'Ovo Cozido',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/boiled-egg',
      quantity: 100,
      unit: 'g',
      calories: 70,
      fat: 4.8,
      carbs: 1.1,
      protein: 5.6,
    },
    {
      food_description:
        'Por 100g - Calorias: 31kcal | Gordura: 0.10g | Carboidratos: 6.80g | Proteína: 0.70g',
      food_id: '842',
      food_name: 'Abóbora Cozida',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/cooked-pumpkin',
      quantity: 100,
      unit: 'g',
      calories: 31,
      fat: 0.1,
      carbs: 6.8,
      protein: 0.7,
    },
    {
      food_description:
        'Por 100g - Calorias: 34kcal | Gordura: 0.30g | Carboidratos: 6.20g | Proteína: 1.20g',
      food_id: '843',
      food_name: 'Alho Cozido',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/cooked-garlic',
      quantity: 100,
      unit: 'g',
      calories: 34,
      fat: 0.3,
      carbs: 6.2,
      protein: 1.2,
    },
    {
      food_description:
        'Por 100g - Calorias: 33kcal | Gordura: 0.40g | Carboidratos: 5.40g | Proteína: 1.10g',
      food_id: '844',
      food_name: 'Repolho Cozido',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/cooked-cabbage',
      quantity: 100,
      unit: 'g',
      calories: 33,
      fat: 0.4,
      carbs: 5.4,
      protein: 1.1,
    },
    {
      food_description:
        'Por 100g - Calorias: 43kcal | Gordura: 0.50g | Carboidratos: 8.20g | Proteína: 1.30g',
      food_id: '845',
      food_name: 'Batata-Doce Cozida',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/cooked-sweet-potato',
      quantity: 100,
      unit: 'g',
      calories: 43,
      fat: 0.5,
      carbs: 8.2,
      protein: 1.3,
    },
    {
      food_description:
        'Por 100g - Calorias: 68kcal | Gordura: 0.40g | Carboidratos: 14.30g | Proteína: 2.00g',
      food_id: '846',
      food_name: 'Feijão Branco Cozido',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/cooked-white-bean',
      quantity: 100,
      unit: 'g',
      calories: 68,
      fat: 0.4,
      carbs: 14.3,
      protein: 2,
    },
    {
      food_description:
        'Por 100g - Calorias: 42kcal | Gordura: 0.40g | Carboidratos: 8.30g | Proteína: 1.50g',
      food_id: '847',
      food_name: 'Feijão Verde Cozido',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/cooked-green-bean',
      quantity: 100,
      unit: 'g',
      calories: 42,
      fat: 0.4,
      carbs: 8.3,
      protein: 1.5,
    },
    {
      food_description:
        'Por 100g - Calorias: 30kcal | Gordura: 0.20g | Carboidratos: 6.00g | Proteína: 1.00g',
      food_id: '848',
      food_name: 'Feijão Preto Cozido',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/cooked-black-bean',
      quantity: 100,
      unit: 'g',
      calories: 30,
      fat: 0.2,
      carbs: 6,
      protein: 1,
    },
    {
      food_description:
        'Por 100g - Calorias: 29kcal | Gordura: 0.20g | Carboidratos: 5.80g | Proteína: 1.30g',
      food_id: '849',
      food_name: 'Feijão Carioca Cozido',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/cooked-pinto-bean',
      quantity: 100,
      unit: 'g',
      calories: 29,
      fat: 0.2,
      carbs: 5.8,
      protein: 1.3,
    },
    {
      food_description:
        'Por 100g - Calorias: 33kcal | Gordura: 0.10g | Carboidratos: 7.10g | Proteína: 1.10g',
      food_id: '850',
      food_name: 'Feijão Manteiga Cozido',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/cooked-butter-bean',
      quantity: 100,
      unit: 'g',
      calories: 33,
      fat: 0.1,
      carbs: 7.1,
      protein: 1.1,
    },
    {
      food_description:
        'Por 100g - Calorias: 50kcal | Gordura: 0.40g | Carboidratos: 9.40g | Proteína: 2.20g',
      food_id: '851',
      food_name: 'Ervilha Cozida',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/cooked-pea',
      quantity: 100,
      unit: 'g',
      calories: 50,
      fat: 0.4,
      carbs: 9.4,
      protein: 2.2,
    },
    {
      food_description:
        'Por 100g - Calorias: 25kcal | Gordura: 0.30g | Carboidratos: 4.90g | Proteína: 1.20g',
      food_id: '852',
      food_name: 'Vagem Cozida',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/cooked-string-bean',
      quantity: 100,
      unit: 'g',
      calories: 25,
      fat: 0.3,
      carbs: 4.9,
      protein: 1.2,
    },
    {
      food_description:
        'Por 100g - Calorias: 37kcal | Gordura: 0.20g | Carboidratos: 8.50g | Proteína: 1.10g',
      food_id: '853',
      food_name: 'Berinjela Cozida',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/cooked-eggplant',
      quantity: 100,
      unit: 'g',
      calories: 37,
      fat: 0.2,
      carbs: 8.5,
      protein: 1.1,
    },
    {
      food_description:
        'Por 100g - Calorias: 36kcal | Gordura: 0.40g | Carboidratos: 7.50g | Proteína: 1.30g',
      food_id: '854',
      food_name: 'Nabo Cozido',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/cooked-turnip',
      quantity: 100,
      unit: 'g',
      calories: 36,
      fat: 0.4,
      carbs: 7.5,
      protein: 1.3,
    },
    {
      food_description:
        'Por 100g - Calorias: 33kcal | Gordura: 0.10g | Carboidratos: 7.10g | Proteína: 1.10g',
      food_id: '855',
      food_name: 'Feijão Manteiga Cozido',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/cooked-butter-bean',
      quantity: 100,
      unit: 'g',
      calories: 33,
      fat: 0.1,
      carbs: 7.1,
      protein: 1.1,
    },
    {
      food_description:
        'Por 100g - Calorias: 37kcal | Gordura: 0.20g | Carboidratos: 8.20g | Proteína: 1.10g',
      food_id: '856',
      food_name: 'Cebola Cozida',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/cooked-onion',
      quantity: 100,
      unit: 'g',
      calories: 37,
      fat: 0.2,
      carbs: 8.2,
      protein: 1.1,
    },
    {
      food_description:
        'Por 100g - Calorias: 23kcal | Gordura: 0.10g | Carboidratos: 4.70g | Proteína: 0.70g',
      food_id: '857',
      food_name: 'Pepino Cozido',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/cooked-cucumber',
      quantity: 100,
      unit: 'g',
      calories: 23,
      fat: 0.1,
      carbs: 4.7,
      protein: 0.7,
    },
    {
      food_description:
        'Por 100g - Calorias: 35kcal | Gordura: 0.10g | Carboidratos: 7.50g | Proteína: 0.80g',
      food_id: '858',
      food_name: 'Pimentão Cozido',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/cooked-pepper',
      quantity: 100,
      unit: 'g',
      calories: 35,
      fat: 0.1,
      carbs: 7.5,
      protein: 0.8,
    },
    {
      food_description:
        'Por 100g - Calorias: 39kcal | Gordura: 0.10g | Carboidratos: 8.70g | Proteína: 1.20g',
      food_id: '859',
      food_name: 'Rabanete Cozido',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/cooked-radish',
      quantity: 100,
      unit: 'g',
      calories: 39,
      fat: 0.1,
      carbs: 8.7,
      protein: 1.2,
    },
    {
      food_description:
        'Por 100g - Calorias: 44kcal | Gordura: 0.40g | Carboidratos: 9.10g | Proteína: 1.00g',
      food_id: '860',
      food_name: 'Tomate Cozido',
      food_type: 'Genérico',
      food_url: 'https://www.fatsecret.com/calories-nutrition/generic/cooked-tomato',
      quantity: 100,
      unit: 'g',
      calories: 44,
      fat: 0.4,
      carbs: 9.1,
      protein: 1,
    },
  ],
  max_results: '50',
  page_number: '0',
  total_results: '2066',
};
